In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
dt = pd.read_csv("diabetes_dataset.csv")
dt.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [3]:
dt.describe()

age  hypertension  heart_disease            bmi  \
count  100000.000000  100000.00000  100000.000000  100000.000000   
mean       41.885856       0.07485       0.039420      27.320767   
std        22.516840       0.26315       0.194593       6.636783   
min         0.080000       0.00000       0.000000      10.010000   
25%        24.000000       0.00000       0.000000      23.630000   
50%        43.000000       0.00000       0.000000      27.320000   
75%        60.000000       0.00000       0.000000      29.580000   
max        80.000000       1.00000       1.000000      95.690000   

         HbA1c_level  blood_glucose_level       diabetes  
count  100000.000000        100000.000000  100000.000000  
mean        5.527507           138.058060       0.085000  
std         1.070672            40.708136       0.278883  
min         3.500000            80.000000       0.000000  
25%         4.800000           100.000000       0.000000  
50%         5.800000           140.000000       0.000000  
75%         6.200000           159.000000       0.000000  
max         9.000000           300.000000       1.000000

In [4]:
dt.dtypes

gender                  object
age                    float64
hypertension             int64
heart_disease            int64
smoking_history         object
bmi                    float64
HbA1c_level            float64
blood_glucose_level      int64
diabetes                 int64
dtype: object

# Data Information

In [5]:
dt.heart_disease.unique()

array([1, 0], dtype=int64)

In [6]:
dt.hypertension.unique()

array([0, 1], dtype=int64)

In [7]:
dt.diabetes.unique()

array([0, 1], dtype=int64)

In [8]:
dt.smoking_history.unique()

array(['never', 'No Info', 'current', 'former', 'ever', 'not current'],
      dtype=object)

In [9]:
dt.gender.unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [10]:
dt.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

# One Hot Encode

In [11]:
encode = pd.get_dummies(dt, prefix=None)
encode

age  hypertension  heart_disease    bmi  HbA1c_level  \
0      80.0             0              1  25.19          6.6   
1      54.0             0              0  27.32          6.6   
2      28.0             0              0  27.32          5.7   
3      36.0             0              0  23.45          5.0   
4      76.0             1              1  20.14          4.8   
...     ...           ...            ...    ...          ...   
99995  80.0             0              0  27.32          6.2   
99996   2.0             0              0  17.37          6.5   
99997  66.0             0              0  27.83          5.7   
99998  24.0             0              0  35.42          4.0   
99999  57.0             0              0  22.43          6.6   

       blood_glucose_level  diabetes  gender_Female  gender_Male  \
0                      140         0              1            0   
1                       80         0              1            0   
2                      158         0              0            1   
3                      155         0              1            0   
4                      155         0              0            1   
...                    ...       ...            ...          ...   
99995                   90         0              1            0   
99996                  100         0              1            0   
99997                  155         0              0            1   
99998                  100         0              1            0   
99999                   90         0              1            0   

       gender_Other  smoking_history_No Info  smoking_history_current  \
0                 0                        0                        0   
1                 0                        1                        0   
2                 0                        0                        0   
3                 0                        0                        1   
4                 0                        0                        1   
...             ...                      ...                      ...   
99995             0                        1                        0   
99996             0                        1                        0   
99997             0                        0                        0   
99998             0                        0                        0   
99999             0                        0                        1   

       smoking_history_ever  smoking_history_former  smoking_history_never  \
0                         0                       0                      1   
1                         0                       0                      0   
2                         0                       0                      1   
3                         0                       0                      0   
4                         0                       0                      0   
...                     ...                     ...                    ...   
99995                     0                       0                      0   
99996                     0                       0                      0   
99997                     0                       1                      0   
99998                     0                       0                      1   
99999                     0                       0                      0   

       smoking_history_not current  
0                                0  
1                                0  
2                                0  
3                                0  
4                                0  
...                            ...  
99995                            0  
99996                            0  
99997                            0  
99998                            0  
99999                            0  

[100000 rows x 16 columns]

In [12]:
encode.dtypes

age                            float64
hypertension                     int64
heart_disease                    int64
bmi                            float64
HbA1c_level                    float64
blood_glucose_level              int64
diabetes                         int64
gender_Female                    uint8
gender_Male                      uint8
gender_Other                     uint8
smoking_history_No Info          uint8
smoking_history_current          uint8
smoking_history_ever             uint8
smoking_history_former           uint8
smoking_history_never            uint8
smoking_history_not current      uint8
dtype: object

# Normalize Data

In [13]:
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()
d = scaler.fit_transform(encode)
data_normalisasi = pd.DataFrame(d, columns=encode.columns)
data_normalisasi.head()

age  hypertension  heart_disease       bmi  HbA1c_level  \
0  1.000000           0.0            1.0  0.177171     0.563636   
1  0.674675           0.0            0.0  0.202031     0.563636   
2  0.349349           0.0            0.0  0.202031     0.400000   
3  0.449449           0.0            0.0  0.156863     0.272727   
4  0.949950           1.0            1.0  0.118231     0.236364   

   blood_glucose_level  diabetes  gender_Female  gender_Male  gender_Other  \
0             0.272727       0.0            1.0          0.0           0.0   
1             0.000000       0.0            1.0          0.0           0.0   
2             0.354545       0.0            0.0          1.0           0.0   
3             0.340909       0.0            1.0          0.0           0.0   
4             0.340909       0.0            0.0          1.0           0.0   

   smoking_history_No Info  smoking_history_current  smoking_history_ever  \
0                      0.0                      0.0                   0.0   
1                      1.0                      0.0                   0.0   
2                      0.0                      0.0                   0.0   
3                      0.0                      1.0                   0.0   
4                      0.0                      1.0                   0.0   

   smoking_history_former  smoking_history_never  smoking_history_not current  
0                     0.0                    1.0                          0.0  
1                     0.0                    0.0                          0.0  
2                     0.0                    1.0                          0.0  
3                     0.0                    0.0                          0.0  
4                     0.0                    0.0                          0.0

# Split Test

In [14]:
from sklearn.model_selection import train_test_split
# Eror nya ada di sini yh. Musti tentukan target apa dan data kamu yang mana saja. Coba dilihat pelan2
X = data_normalisasi.drop(['diabetes'],axis=1)
y = data_normalisasi['diabetes']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [15]:
X_train.shape

(80000, 15)

In [16]:
y_train.shape

(80000,)

In [17]:
X_test.shape

(20000, 15)

# SVM

In [18]:
#z = np.array(X_train).reshape(-1, 1)
#z

In [19]:
from sklearn import svm
model_svm = svm.SVC()

In [20]:
model_svm.fit(X_train, y_train)

SVC()

In [21]:
model_svm.score(X_test,y_test)

0.96185